---
title: "R Notebook"
output: html_notebook
---

Reading in the data
```{r message=FALSE}
library(tidyverse)
ppmr_full <-
    read_tsv("Predator_and_prey_body_sizes_in_marine_food.csv",
             na = c("", "n/a"),
             guess_max = 10000)
ppmr_full
```
We select only the relevant columns and remove predator species with fewer than 1000 observations.
```{r}
ppmr <- ppmr_full %>% 
    select(Species = `Predator common name`,
           w_pred = `SI predator mass`,
           w_prey = `SI prey mass`,
           lifestage = `Predator lifestage`) %>% 
    mutate(lifestage = recode(lifestage, "Adult" = "adult")) %>% 
    mutate(l = log(w_pred / w_prey)) %>% 
    group_by(Species) %>% 
    filter(n() > 1000)
ppmr
```
This leaves
```{r}
unique(ppmr$Species)
```
We take a look at the scatterplots to see that the assumption that the log predator/prey
mass ratio is independent of the predator size is not unreasonable.
```{r}
ppmr %>% ggplot(aes(w_pred, w_pred / w_prey)) +
    geom_jitter(aes(colour = lifestage)) +
    scale_x_log10() +
    scale_y_log10() +
    facet_wrap(~Species, scales = "free_x")
```

```{r}
grid <- with(ppmr, seq(0, max(l), length = 100))
normaldens <- plyr::ddply(ppmr, "Species", function(df) {
  data.frame( 
    l = grid,
    density = dnorm(grid, mean(df$l), sd(df$l))
  )
})

ggplot(ppmr) +
    geom_density(aes(l)) +
    facet_wrap(~Species, scales = "free_y", ncol = 4) +
    xlab("Log of predator/prey mass ratio")  +
    geom_line(aes(l, density), data = normaldens,
                  colour = "blue")
```

```{r}
ppmr <- ppmr %>%
    mutate(weight = w_prey / sum(w_prey))

normaldens <- plyr::ddply(ppmr, "Species", function(df) {
  data.frame( 
    l = grid,
    density = dnorm(grid, weighted.mean(df$l, df$weight), 
                    sqrt(sum(df$weight * 
                                 (df$l - weighted.mean(df$l, df$weight))^2)))
  )
})

ggplot(ppmr) +
    geom_density(aes(l, weight = weight)) +
    facet_wrap(~Species, scales = "free_y", ncol = 4) +
    xlab("Log of predator/prey mass ratio") +
    ylab("Biomass density") +
    geom_line(aes(l, density), data = normaldens,
                  colour = "blue")
    
```

```{r}
alpha <- 1/3
lambda <- 2
ppmr <- ppmr %>%
    mutate(weight = w_prey^(lambda - 1 - alpha),
           weight = weight / sum(weight))

normaldens <- plyr::ddply(ppmr, "Species", function(df) {
  data.frame( 
    l = grid,
    density = dnorm(grid, weighted.mean(df$l, df$weight), 
                    sqrt(sum(df$weight * 
                                 (df$l - weighted.mean(df$l, df$weight))^2)))
  )
})

ggplot(ppmr) +
    geom_density(aes(l, weight = weight)) +
    facet_wrap(~Species, scales = "free_y", ncol = 4) +
    xlab("Log of predator/prey mass ratio") +
    ylab("Kernel") +
    geom_line(aes(l, density), data = normaldens,
                  colour = "blue")
    
```

```{r}
ppmr %>% 
    filter(w_prey > w_pred)
```

