---
title: "R Notebook"
output: html_notebook
---

## A title
Some explanation of what you are doing. Then some code in an R code block.
We should use file paths relative to the directory this notebook is in.
```{r}
params <- readRDS("params_36.rds")
```
Now that we have the params object we can just get the bins from there
```{r}
bins <- params@w
```
Let's load the data
```{r}
library(readr)
fish_sizes_sp <- read_csv("fish_sizes_sp.csv", skip = 1)
```

Now we can make plots. This too needs to go into an R code block.
```{r}
hist(fish_sizes_sp$Dourada, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$Choupa, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$baila, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$toadfish, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$Eel, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$Pargo, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$garfish, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$Seabass, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$sole, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$Mucharra, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$Safia, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$silverside, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$`red mullet`, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$`Sargo`, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$`Salema`, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$`wrasse`, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$`goby`, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$`anchovy`, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$`sardine`, breaks = bins, xlim = y, freq = TRUE)
hist(fish_sizes_sp$`grey mullet`, breaks = bins, xlim = y, freq = TRUE)
```






