---
title: "Mouth area"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

From the papers we have an allometric expression for the mouth area $A$ as
a function of predator length $L$:
$$
A = a_A L^{b_A}.
$$
The values of $a_A$ and $b_A$ are given for different species in the papers,
with $L$ measured in cm and $A$ measured in cm^2.

We also have an allometric relationship between the predator length $L$ and the 
predator weight $w$:
$$
w = a L^b.
$$
We can invert that to get $L$ in terms of $w$:
$$
L = \left(\frac{w}{a}\right)^{1/b}.
$$
We now make the assumption that the preferred prey size $w_p$ scales with the mouth
area as
$$
w_p = a_p A^{b_p}.
$$
We don't know $a_p$ and $b_p$ but at least $b_p$ we will be able to eliminate
below. Substituting the expression for $A$ and then expressing $L$ by $w$ gives
$$
w_p = a_p \left(a_A \left(\frac{w}{a}\right)^{b_A/b}\right)^{b_p}
= a_p\ a_A^{b_p}\ a^{-(b_Ab_p)/b}\ w^{(b_Ab_p)/b}.
$$
Now we know that we want the preferred prey size $w_p$ to be a fixed fraction
of the pedator size $w$,
$$
w_p = w / \beta,
$$
where $\beta$ is the preferred predator/prey size ratio $\beta = w/w_p$.
Comparing the two above equations tells us that $(b_Ab_p)/b = 1$ and hence
$$
b_p = \frac{b}{b_A}
$$
and
$$
\beta = w/w_p = \frac{a}{a_p}a_A^{b/b_A}.
$$
We don't know $a_p$, so let us just choose some reasonable value, say 
$a_p = 0.1$.

