
params_data <- read.csv("./vignettes/NS_species_params.csv")
inter <- read.csv("./vignettes/inter.csv", row.names=1)
inter <- as(inter, "matrix")
mytimes <- seq(0.5,10,0.1)
param1 <- MizerParams(params_data, interaction = inter, no_w = 100)
test<-project(param1,effort=0.5, dt = 0.25, t_save = 1,t_max=500)
plot(test)
plot(param1@w,param1@initial_n[1,],log="xy")
plot(param1@w_full,param1@initial_n_pp,log="xy")
