# Source the mizer code without loading it as a package
source('./R/MizerParams-class.r')
source('./R/MizerSim-class.r')
source('./R/project_methods.r')
source('./R/selectivity_funcs.r')
source('./R/summary_methods.r')
source('./R/wrapper_functions.R')
source('./R/plots.r')
source('./R/project.r')
library(ggplot2)
library(grid)
library(methods)
library(plyr)
library(reshape2)