# Source the mizer code without loading it as a package
source('C:/github/mizer/R/MizerParams-class.r')
source('C:/github/mizer/R/MizerSim-class.r')
source('C:/github/mizer/R/project_methods.r')
source('C:/github/mizer/R/selectivity_funcs.r')
source('C:/github/mizer/R/summary_methods.r')
source('C:/github/mizer/R/wrapper_functions.R')
source('C:/github/mizer/R/plots.r')
source('C:/github/mizer/R/project.r')
library(ggplot2)
library(grid)
library(methods)
library(plyr)
library(reshape2)